config/routes.rb
Rails.application.routes.draw do
  resources :line_items

  resources :carts

  get 'gallery/index'

  get 'gallery/checkout'
  post 'gallery/checkout'

  get 'gallery/search'
  post 'gallery/search'
  
  get "gallery/shopping_complete"

  resources :cakestores

  resources :stores

  get 'account/index'
  get 'account/signin'
  post 'account/signin'
  post "signin" => "account#login"
  get 'account/logout'
  get 'account/signup'
  post 'account/signup'
  post "signup" => "account#register"
  root 'account#index'
  get 'account/contact'
  post 'account/contact'
  get 'account/pastryshop'
  get 'account/services'
  get 'account/about'
  get 'account/forget_password'
  post 'account/forget_password'
  get 'account/reset_password'
  post 'account/reset_password'
 get "admin/login"
 post "admin/login"
  get "admin/logout"
  

end

app/models/cakestore.rb
class Cakestore < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/controllers/cakestores_controller.rb
class CakestoresController < ApplicationController
  before_action :set_cakestore, only: [:show, :edit, :update, :destroy]
  before_filter :authorize
  layout "cakestores"

  # GET /cakestores
  # GET /cakestores.json
  def index
    @cakestores = Cakestore.all
  end

  # GET /cakestores/1
  # GET /cakestores/1.json
  def show
  end

  # GET /cakestores/new
  def new
    @cakestore = Cakestore.new
  end

  # GET /cakestores/1/edit
  def edit
  end

  # POST /cakestores
  # POST /cakestores.json
  def create
    @cakestore = Cakestore.new(cakestore_params)

    respond_to do |format|
      if @cakestore.save
        format.html { redirect_to @cakestore, notice: 'Cakestore was successfully created.' }
        format.json { render :show, status: :created, location: @cakestore }
      else
        format.html { render :new }
        format.json { render json: @cakestore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cakestores/1
  # PATCH/PUT /cakestores/1.json
  def update
    respond_to do |format|
      if @cakestore.update(cakestore_params)
        format.html { redirect_to @cakestore, notice: 'Cakestore was successfully updated.' }
        format.json { render :show, status: :ok, location: @cakestore }
      else
        format.html { render :edit }
        format.json { render json: @cakestore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cakestores/1
  # DELETE /cakestores/1.json
  def destroy
    @cakestore.destroy
    respond_to do |format|
      format.html { redirect_to cakestores_url, notice: 'Cakestore was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cakestore
      @cakestore = Cakestore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cakestore_params
      params.require(:cakestore).permit(:cake_name, :description, :cake_weight, :price, :quantity, :occasion, :image)
    end
    
    def authorize
      if session[:admin].nil?
      flash[:notice] = "Please log in"
      redirect_to :controller => :admin, :action => :login
      end
    end
    
end

app/helpers/cakestores_helper.rb
module CakestoresHelper
end

app/views/cakestores/_form.html.erb
<%= form_for(@cakestore) do |f| %>
  <% if @cakestore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cakestore.errors.count, "error") %> prohibited this cakestore from being saved:</h2>

      <ul>
      <% @cakestore.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cake_name %><br>
    <%= f.text_field :cake_name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :cake_weight %><br>
    <%= f.number_field :cake_weight %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :occasion %><br>
    <%= f.text_field :occasion %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cakestores/edit.html.erb
<h1>Editing cakestore</h1>

<%= render 'form' %>

<%= link_to 'Show', @cakestore %> |
<%= link_to 'Back', cakestores_path %>

app/views/cakestores/index.html.erb
<h1>Listing cakestores</h1>

<table>
  <thead>
    <tr>
      <th>Cake name</th>
      <th>Description</th>
      <th>Cake weight</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Occasion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cakestores.each do |cakestore| %>
      <tr>
        <td><%= cakestore.cake_name %></td>
        <td><%= cakestore.description %></td>
        <td><%= cakestore.cake_weight %></td>
        <td><%= cakestore.price %></td>
        <td><%= cakestore.quantity %></td>
        <td><%= cakestore.occasion %></td>
        <td><%= link_to 'Show', cakestore %></td>
        <td><%= link_to 'Edit', edit_cakestore_path(cakestore) %></td>
        <td><%= link_to 'Destroy', cakestore, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Cakestore', new_cakestore_path %>

app/views/cakestores/new.html.erb
<h1>New cakestore</h1>

<%= render 'form' %>

<%= link_to 'Back', cakestores_path %>

app/views/cakestores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cake image:</b>
  <%= image_tag @cakestore.image.url ,:height=>"200",:width=>"200"%>
</p>

<p>
  <strong>Cake name:</strong>
  <%= @cakestore.cake_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @cakestore.description %>
</p>

<p>
  <strong>Cake weight:</strong>
  <%= @cakestore.cake_weight %>
</p>

<p>
  <strong>Price:</strong>
  <%= @cakestore.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @cakestore.quantity %>
</p>

<p>
  <strong>Occasion:</strong>
  <%= @cakestore.occasion %>
</p>

<%= link_to 'Edit', edit_cakestore_path(@cakestore) %> |
<%= link_to 'Back', cakestores_path %>